# Generated by Django 2.0.4 on 2018-04-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='Message',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='Name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='Phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
