# Generated by Django 2.0.4 on 2018-04-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180429_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='Email',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='Message',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='Phone',
        ),
        migrations.AddField(
            model_name='contactform',
            name='message',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='contactform',
            name='name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='contactform',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
