# Generated by Django 2.0.4 on 2018-04-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180429_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='State',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='street_address',
            field=models.CharField(default='', max_length=50),
        ),
    ]
