# Generated by Django 2.0.4 on 2018-05-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180429_2316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='State',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Zipcode',
            new_name='zipcode',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
